Do not produce compiler errors when deprecated declarations are used.
At some unknown point in time it started failing due to the code referencing some
deprecated `opstats.proto` enum values. Until our use of those deprecated enums is
fully turned down, we should not cause the build to fail on this.

An example error:
```
fcp/client/federated_task_environment.cc:199:41: error: 'EVENT_KIND_UPLOAD_STARTED' is deprecated [-Werror,-Wdeprecated-declarations]
      opstats::OperationalStats::Event::EVENT_KIND_UPLOAD_STARTED);
```

PiperOrigin-RevId: 430327585